apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: celeborn-worker-graviton
spec:
  disruption:
    budgets:
    - nodes: 100%
    consolidateAfter: 30s
    consolidationPolicy: WhenEmpty
  limits:
    cpu: 1000
  template:
    metadata:
      labels:
        NodeGroupType: CelebornWorker 
        provisioner: celeborn-worker-graviton
        type: karpenter
    spec:
      expireAfter: 'Never'
      nodeClassRef:
        group: karpenter.k8s.aws  # Updated since only a single version will be served
        kind: EC2NodeClass
        name: celeborn-worker-graviton
      requirements:
      - key: topology.kubernetes.io/zone
        operator: In
        values:
        - us-west-2a
      - key: karpenter.sh/capacity-type
        operator: In
        values:
        - on-demand
      - key: node.kubernetes.io/instance-type
        operator: In
        values:
        - i3en.2xlarge
  weight: 10
